version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.${APPLICATION_TYPE}
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '80:3000'